Repository my-otter-self/MAS_selfharm, pull requests merged in 2022-04, with the labels that each got.

#28 Pre-release merge for further rebasing of all the existing PRs
  script-diary.rpy
  script-first-aid.rpy
  script-intro.rpy
  script-milestones.rpy
  script-promise.rpy
  script-questions.rpy
  script-therapy.rpy
  selfharm.rpy
  techniques.rpy
  zz_player_model.rpy
Labels: untested, awaiting, work in progress, refactoring

#3 RANDOM STARTER TOPIC
  script-intro.rpy
  selfharm.rpy
Labels: work in progress

#8 RANDOM EVENT - DIARY
  script-diary.rpy
  selfharm.rpy
Labels: work in progress

#9 PROBING QUESTIONS (NON RANDOM)
  script-questions.rpy
  selfharm.rpy
Labels: work in progress

#12 RELAPSE DIALOGUE (NON-RANDOM)
  script-promise.rpy
  selfharm.rpy
Labels: work in progress

#16 PROMISE DIALOGUE (NON-RANDOM)
  script-milestones.rpy
  script-promise.rpy
  selfharm.rpy
Labels: work in progress

#35 THERAPY TOPICS
  script-therapy.rpy
Labels: ready for merge

#36 Rework CI and dev scripts
  .github/scripts/compile-submod.sh
  .github/scripts/extract-version.sh
  .github/scripts/fetch-ddlc-mas.sh
  .github/scripts/fetch-renpy-sdk.sh
  .github/workflows/lint-on-pull-request.yml
  .github/workflows/package-on-release.yml
  .gitignore
  .scripts/compile-submod.sh
  scripts/compile.sh
  scripts/lint.sh
Labels: refactoring, ready for merge, meta

#37 CHECKUPS
  script-checkup.rpy
Labels: work in progress

#34 RANDOM EVENTS
  script-events.rpy
Labels: ready for review

#32 INTRO TOPIC
  script-intro.rpy
Labels: ready for review

#31 RANDOM TECHNIQUES
  script-techniques.rpy
Labels: work in progress

#30 PROBING QUESTIONS
  script-questions.rpy
Labels: ready for review

#21 MEDICATION REMINDERS (RANDOM)
  script-reminders.rpy
Labels: work in progress

#5 RANDOM EVENT - SAD MONIKA #1
  script-events.rpy
Labels: work in progress

#1 SELF-HARM URGE EVENT! (NON RANDOM)
  script-urge.rpy
Labels: ready for review
